### ISSUE TITLE
Crash when launching the app

### ISSUE THREAD

**Issue by squall09s** [passbase/passbase-sdk#2]
Hello,

I think I discovered a small problem on the Master branch. Crash when launching the app.
Could I have FTP access to your computer please?

Have a good day,

![image](https://user-images.githubusercontent.com/3595533/88932582-8eb28d80-d27e-11ea-843f-698704705346.png)

**Comment by mattk90** [comment]
Thanks for reporting this issue @squall09s 

Let us quickly try to reproduce this. Can you fill out / add the following form, please? I already assumed some stuff in the brackets based on what you reported.

1. On which platform/device did you experience the bug? (Native iOS?)
2. What is the expected behavior? (Initializing the SDK I assume?)
3. What is the actual behavior?  (I can )
4. Steps to reproduce the bug for us.
5. Create a sample project and where the error exists. Feel free invite @skorostetskyi or me to this here.

**Comment by skorostetskyi** [comment]
Thanks for the report.
The fix is on its way. It happens because SDK tries to customize PassbaseButton that does not exist. Just add PassbaseButton to your ViewController as a quick fix. But tomorrow we will push SDK update for that.

**Comment by skorostetskyi** [comment]
v1.9.1 has a fix for the issue

**Comment by squall09s** [comment]
Hello,
I confirm that version 1.9.1 corrects the problem.
It's perfect,

thank you
